// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvN3DSOhPfEeKzSl4PZrY3xdNgFnP9p4',
    appId: '1:128841287591:web:e091468586c58799b41882',
    messagingSenderId: '128841287591',
    projectId: 'adrenaline-first-app',
    authDomain: 'adrenaline-first-app.firebaseapp.com',
    storageBucket: 'adrenaline-first-app.appspot.com',
    measurementId: 'G-1PSL8R7VZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0g07jv9GK9CstevLOpWPVeq1pKjE5vA',
    appId: '1:128841287591:android:8030470e55fdb9c0b41882',
    messagingSenderId: '128841287591',
    projectId: 'adrenaline-first-app',
    storageBucket: 'adrenaline-first-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtUPxkB0ZNkpcGsC_DL6KyU4QFMFOdDo',
    appId: '1:128841287591:ios:009ba5f9baa36683b41882',
    messagingSenderId: '128841287591',
    projectId: 'adrenaline-first-app',
    storageBucket: 'adrenaline-first-app.appspot.com',
    iosClientId: '128841287591-u0l20stb8242t639083ho2tb42fic7ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAtUPxkB0ZNkpcGsC_DL6KyU4QFMFOdDo',
    appId: '1:128841287591:ios:009ba5f9baa36683b41882',
    messagingSenderId: '128841287591',
    projectId: 'adrenaline-first-app',
    storageBucket: 'adrenaline-first-app.appspot.com',
    iosClientId: '128841287591-u0l20stb8242t639083ho2tb42fic7ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
